export const ActionTypes={
    LOGIN:"LOGIN",
    GET_TOKEN:"GET_TOKEN",
    GET_ROOTINFO:"GET_ROOTINFO",
    GET_ALL_USER_INFO:"GET_ALL_USER_INFO",
    UPDATE_AVATAR:"UPDATE_AVATAR",
    SET_BLOGS:"SET_BLOGS",
    SET_CLOSE:"SET_CLOSE",
    SELECTED_BLOG:"SELECTED_BLOG",
    REMOVE_SELECTED_BLOG:"REMOVE_SELECTED_BLOG"
};